DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'edem_app') THEN
    CREATE ROLE edem_app LOGIN PASSWORD 'edem_app_2026';
  ELSE
    ALTER ROLE edem_app WITH LOGIN PASSWORD 'edem_app_2026';
  END IF;
END
$$;

GRANT CONNECT ON DATABASE vprok TO edem_app;
\c vprok
GRANT USAGE ON SCHEMA public TO edem_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO edem_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO edem_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO edem_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO edem_app;
